import CTASection from "@/components/CTA";
import FeaturesSection from "@/components/Features";
import Footer from "@/components/Footer";
import HeroSection from "@/components/Hero";
import Nav from "@/components/Nav";
import TestimonialSection from "@/components/Testimonial";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className="bg-blob bg-no-repeat bg-contain bg-[right_-101px_top_-32px] md:bg-[right_-213px_top_-171px] xl:md:bg-[right_-22px_top_-107px]">
          <Nav />
          <HeroSection />
        </header>
        <FeaturesSection />
        <TestimonialSection />
        <CTASection />
      </main>
      <Footer />
    </>
  );
}
